"""add_bill_extraction_fields_and_bill_items

Revision ID: 378472662208
Revises: 2b5a44e75983
Create Date: 2026-04-26 06:28:26.512449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378472662208'
down_revision: Union[str, Sequence[str], None] = '2b5a44e75983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_items_bill_id'), 'bill_items', ['bill_id'], unique=False)
    op.add_column('bills', sa.Column('merchant', sa.String(length=256), nullable=True))
    op.add_column('bills', sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('bills', sa.Column('currency', sa.String(length=8), nullable=True))
    op.add_column('bills', sa.Column('billed_at', sa.Date(), nullable=True))
    op.add_column('bills', sa.Column('raw_ocr_text', sa.Text(), nullable=True))
    op.add_column('bills', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bills', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'reviewed_at')
    op.drop_column('bills', 'extracted_at')
    op.drop_column('bills', 'raw_ocr_text')
    op.drop_column('bills', 'billed_at')
    op.drop_column('bills', 'currency')
    op.drop_column('bills', 'total')
    op.drop_column('bills', 'merchant')
    op.drop_index(op.f('ix_bill_items_bill_id'), table_name='bill_items')
    op.drop_table('bill_items')
    # ### end Alembic commands ###
