"""add_splits_participants_item_shares

Revision ID: 3f19de8605c2
Revises: 378472662208
Create Date: 2026-04-26 13:31:44.247187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f19de8605c2'
down_revision: Union[str, Sequence[str], None] = '378472662208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', name='uq_splits_bill_id')
    )
    op.create_index(op.f('ix_splits_bill_id'), 'splits', ['bill_id'], unique=False)
    op.create_table('split_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('split_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['split_id'], ['splits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('split_id', 'display_name', name='uq_participant_name')
    )
    op.create_index(op.f('ix_split_participants_split_id'), 'split_participants', ['split_id'], unique=False)
    op.create_table('split_item_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('split_id', sa.UUID(), nullable=False),
    sa.Column('bill_item_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_item_id'], ['bill_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['split_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['split_id'], ['splits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_item_id', 'participant_id', name='uq_item_participant')
    )
    op.create_index(op.f('ix_split_item_shares_bill_item_id'), 'split_item_shares', ['bill_item_id'], unique=False)
    op.create_index(op.f('ix_split_item_shares_participant_id'), 'split_item_shares', ['participant_id'], unique=False)
    op.create_index(op.f('ix_split_item_shares_split_id'), 'split_item_shares', ['split_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_split_item_shares_split_id'), table_name='split_item_shares')
    op.drop_index(op.f('ix_split_item_shares_participant_id'), table_name='split_item_shares')
    op.drop_index(op.f('ix_split_item_shares_bill_item_id'), table_name='split_item_shares')
    op.drop_table('split_item_shares')
    op.drop_index(op.f('ix_split_participants_split_id'), table_name='split_participants')
    op.drop_table('split_participants')
    op.drop_index(op.f('ix_splits_bill_id'), table_name='splits')
    op.drop_table('splits')
    # ### end Alembic commands ###
