"""add_username_to_users

Revision ID: 70a10272cba2
Revises: 3f19de8605c2
Create Date: 2026-04-30 20:34:25.924475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a10272cba2'
down_revision: Union[str, Sequence[str], None] = '3f19de8605c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    # Backfill existing rows: derive from email prefix, strip non-alphanumeric, append 6 hex chars from id
    op.execute(
        "UPDATE users SET username = "
        "LOWER(REGEXP_REPLACE(SPLIT_PART(email, '@', 1), '[^a-z0-9]', '', 'g')) "
        "|| SUBSTRING(REPLACE(id::text, '-', '') FROM 1 FOR 6) "
        "WHERE username IS NULL"
    )
    op.alter_column('users', 'username', nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
