"""add_split_requests_and_settlements

Revision ID: cad8c8900b73
Revises: 70a10272cba2
Create Date: 2026-05-01 00:57:27.914357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad8c8900b73'
down_revision: Union[str, Sequence[str], None] = '70a10272cba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('split_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_split_settlements_from_user_id'), 'split_settlements', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_split_settlements_to_user_id'), 'split_settlements', ['to_user_id'], unique=False)
    op.create_table('split_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', 'from_user_id', 'to_user_id', name='uq_split_request_bill_pair')
    )
    op.create_index(op.f('ix_split_requests_bill_id'), 'split_requests', ['bill_id'], unique=False)
    op.create_index(op.f('ix_split_requests_from_user_id'), 'split_requests', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_split_requests_to_user_id'), 'split_requests', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_split_requests_to_user_id'), table_name='split_requests')
    op.drop_index(op.f('ix_split_requests_from_user_id'), table_name='split_requests')
    op.drop_index(op.f('ix_split_requests_bill_id'), table_name='split_requests')
    op.drop_table('split_requests')
    op.drop_index(op.f('ix_split_settlements_to_user_id'), table_name='split_settlements')
    op.drop_index(op.f('ix_split_settlements_from_user_id'), table_name='split_settlements')
    op.drop_table('split_settlements')
    # ### end Alembic commands ###
